ExperienceApp/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'Blog' => 'pages#Blog' ,as: :Blog
  get 'Profile' => 'pages#Profile', as: :Profile
  get 'ricerca' => 'pages#ricerca', as: :ricerca
  get 'index' => 'posts#index' ,as: :index
  get 'Info' => 'pages#Info', as: :Info
  get 'Contact' => 'pages#Contact', as: :Contact
  resources :users

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root to: 'welcome#homepage'
  resources :welcome


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ExperienceApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ExperienceApp/app/models/post.rb
class Post < ApplicationRecord
	

	def should_generate_new_friendly_id?
		title_changed?
	end
end

ExperienceApp/app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.typeU = '0'
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

ExperienceApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

ExperienceApp/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  require 'open-uri'
  require 'json'
  require 'uri'
  

  def Blog
  end

  def Profile
  end

  def Info
  end

  def Contact
  end

  def ricerca

    
    
    url="https://pixabay.com/api/?key=9214446-17f0f2b39aa068c45afbc3a2d&q=photo&per_page=200"
    prova=open(url,&:read)
    @data = JSON.parse(prova)
    @img_urls=[]
    @data ['hits'].each do |el|
      @img_urls << el['largeImageURL']
    end   
  end
end

ExperienceApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body_text, :description,:banner_image_url)
    end
end

ExperienceApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

ExperienceApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

ExperienceApp/app/helpers/application_helper.rb
module ApplicationHelper
end

ExperienceApp/app/helpers/blog_helper.rb
module BlogHelper
end

ExperienceApp/app/helpers/pages_helper.rb
module PagesHelper
end

ExperienceApp/app/helpers/posts_helper.rb
module PostsHelper
end

ExperienceApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

ExperienceApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ExperienceApp/app/views/pages/Blog.html.erb
<h1>Pages#Blog</h1>
<p>Find me in app/views/pages/Blog.html.erb</p>

ExperienceApp/app/views/pages/Contact.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" href="../assets/stylesheets/animate.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

* {
    box-sizing: border-box;
}
//maps
#map {
    height: 100%;
}
      /* Optional: Makes the sample page fill the window. */
    html, body {
    height: 100%;
    margin: 0;
    padding: 0;
}
/* Style inputs */
input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
}

input[type=submit] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: #45a049;
}

input[type=reset] {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    cursor: pointer;
}

input[type=reset]:hover {
    background-color: #45a049;
}
/* Style the container/contact section */
.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 10px;

}

/* Create two columns that float next to eachother */
.column {
    float: left;
    width: 50%;
    margin-top: 6px;
    padding: 20px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
    .column, input[type=submit] {
        width: 100%;
        margin-top: 0;
    }
}


/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: #333;
}

/* Style the topnav links */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change color on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}


/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {
        width: 100%;
        padding: 0;
    }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
    .topnav a {
        float: none;
        width: 100%;
    }
}
</style>
</head>
<body>



<div class="topnav">
  <a href="http://localhost:3000/Contact">CONTACT</a>
  <a href="http://localhost:3000/Info">INFO</a>

  <a href="http://localhost:3000" style="float:right">TO BACK</a>
</div>

<h1 class="animated zoomIn" style="font-size:45px; align:center"><b>CONTACT US</b></h1>
<div class="container">

  <div style="text-align:center">
  </div>
  <div class="row">
    <div class="column">
      <div id="map" style="width:100%;height:500px"></div>
    </div>
    <div class="column">
      <h1>Send us a message if you have problems or questions!</h1>
      <br>
      <form method="post" enctype="text/plain">
        <b>Oggetto:</b><br>
        <input type="text" name="oggetto"><br><br>
        <b>Testo:</b><br>
        <textarea name="testo" rows="10"></textarea><br><br>
	<input type="submit" value="Send" onclick="f()">
	<input type="reset" value="Cancel"><br>
      </form>
      <script>
	function f(){
	  alert("E-mail inviata con successo!");
	}
      </script>
    </div>
  </div>
</div>


  <div id="map"></div>
    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.
      var map, infoWindow;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 6
        });
        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            infoWindow.setPosition(pos);
            infoWindow.setContent('Location found.');
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLOIkvikuBHKlXvYzjRUY1iKyB1yzfhaI&callback=initMap">
    </script>



</body>
</html>

ExperienceApp/app/views/pages/Info.html.erb
<!DOCTYPE html>
<html>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<head>
<style type="text/css">
  

/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: #333;
}

/* Style the topnav links */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change color on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}


/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {   
        width: 100%;
        padding: 0;
    }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
    .topnav a {
        float: none;
        width: 100%;
    }
}

</style>
</head>

<body>
  <div class="topnav">
    <a href="http://localhost:3000/Info">INFO</a>
  <a href="http://localhost:3000/Contact">CONTACT</a>
  
 
  <a href="http://localhost:3000" style="float:right">TO BACK</a>
</div>

<div class="w3-light-grey w3-padding-64 w3-margin-bottom w3-center">
  <h1 class="w3-jumbo">INFORMATION</h1>
</div>

<div class="w3-row-padding w3-content" style="max-width:1400px">
  <div class="w3-twothird">
    <img src="https://images.pexels.com/photos/1051077/pexels-photo-1051077.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"  style="width:100%">
    
   
  </div>
  <div class="w3-third">
    <div class="w3-container w3-light-grey">
      <h2>What is  Experience?</h2>
      <p class="w3-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
    </div>
    <br>
    <div class="w3-container w3-light-grey w3-justify">
      <h2>What can I do?</h2>
      <p class="w3-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborumLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <br>
  
  </div>
</div>

</body>
</html>

ExperienceApp/app/views/pages/Profile.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
* {
    box-sizing: border-box;
}

body {
    font-family: Arial;
    padding: 10px;
    background-color:#CCCCCC  ;
}

.circular--landscape {
  display: inline-block;
  position: relative;
  width: 200px;
  height: 200px;
  overflow: hidden;
  border-radius: 50%;
}

.circular--landscape img {
  width: auto;
  height: 100%;
  margin-left: -50px;
}


/* Style the top navigation bar */
.topnav {
      overflow: hidden;
    background-color: #333;
    list-style-type: none;
    margin: 0;
    position: -webkit-sticky; /* Safari */
    position: sticky;
    top: 0;
}

/* Style the topnav links */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change color on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {
    float: center;
    padding-right: 40px;
  
}

/* Right column */
.rightcolumn {
   
    width: 25%;
    background-color: #CCCCCC;
    padding-right: 40px;
}

/* Fake image */
.fakeimg {
    background-color: #aaa;
    width: 100%;
    padding: 20px;
}

/* Add a card effect for articles */
.card {
    background-color: white;
    padding: 20px;
    margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* Footer */
.footer {
    padding: 20px;
    text-align: center;
    background: #ddd;
    margin-top: 20px;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {
        width: 100%;
        padding: 0;
    }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
    .topnav a {
        float: none;
        width: 100%;
    }
}
</style>

    <script>
        function myFunction() {
            var type;
            if (confirm("VUOI DIVENTARE UN UNTENTE GOLD?")) {
                type="gold";
            } else {
                type="free";
            }
            localStorage.setItem("typeU" ,type);
        }
          function my() {
            var type;
            if (confirm("VUOI restare"+" "+localStorage.typeU)) {
                type="gold";
            } else {
                type="free";
            }
            localStorage.setItem("typeU" ,type);
        }
    </script>


</head>
<body>




<div class="topnav">
  <a href="http://localhost:3000/posts">Posts</a>
  <a href="http://localhost:3000/Profile">Profile</a>
  <a href="http://localhost:3000/ricerca" >FIND INSPIRATION</a>
  <a href="http://localhost:3000/posts/new">New Post</a>
  <a href="http://localhost:3000" style="float:right">To Back</a>
</div>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h2>WHAT DO YOU WANT TO BE?</h2>

      <img src="https://images.pexels.com/photos/257897/pexels-photo-257897.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260" width="100%">
      <br>
      <p id="o" >
      <br>
      SELEZIONA UTENTE:
      <ul>
        <li>utente free  è l'utente base</li>
        <li>utente gold è l'untente premium</li>
        
      </ul>
     
      <br>




    </div>
    <div class="card">



      <% if current_user %>
       <h2>Logout</h2>
        Signed in as <strong><%=current_user.name%></strong>!
        <a  onClick="my()" <%= link_to "Sign out", signout_path, id: "sign_out" %> />
      <% else %>
      <h2>Login</h2>

        <a onclick="myFunction()" href="/auth/google_oauth2">

        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEsXB9VU6fVwxUqcZZFgAqSTQiQfHZI2pD1ValAKXZFGhnBZe9" alt="HTML tutorial" style="width:42px;height:42px;border:0">
      </a>
      <% end %>

     
    </div>
  </div>
 
</div>



</body>
<script type="text/javascript">
  function validate(){
    if(localStorage.type==free){
      document.getElementById("o").innerHTML = "Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.";
    }else if(localStorage.type==gold){
       document.getElementById("o").innerHTML = "Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.CACAAAAAAAAs";

    }
  }
  /*
  function myFunctionPoraccio() {
  document.getElementById("poraccio").innerHTML = "Hello World";
 }

  function myFunctionCavaliere() {
  document.getElementById("cavaliere").innerHTML = "Hello ";
}*/
function validateUtente() {
    if (document.getElementById("option1").checked == true) {
        localStorage.setItem("type", "free");
        alert("Local Test: " + localStorage.type);
        document.getElementById("demo").innerHTML = "Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.";



    }
    else if (document.getElementById("option2").checked == true) {
      localStorage.setItem("type", "gold");
        alert("Local Test: " + localStorage.type);
        document.getElementById("demo").innerHTML = "Hello n culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation  ";
    }

    else {
        // DO NOTHING
        }
    }


</script>
</html>

ExperienceApp/app/views/pages/ricerca.html.erb
<% provide(:page_title, 'Search') %>
<% provide(:blog_title, 'active') %>
<p id="notice"><%= notice %></p>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
<head>
<style type="text/css">

body {
    font-family: Arial;
   
    background-color:#CCCCCC  ;
}
div.container {
  text-align: center;
  padding: 10px 15px;
}

/* Style the top navigation bar */
.topnav {
    overflow: hidden;
    background-color: #333;
    list-style-type: none;
    margin: 0;
   
   
   
    position: -webkit-sticky; /* Safari */
    position: sticky;
    top: 0;
}

/* Style the topnav links */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change color on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {   
        width: 100%;
        padding: 0;
    }
}

/* Responsive layout - when the screen is less than 400px wide, make the navigation links stack on top of each other instead of next to each other */
@media screen and (max-width: 400px) {
    .topnav a {
        float: none;
        width: 100%;
    }
}
</style>
<div class="topnav">
    <a href="http://localhost:3000/posts">POST</a>
  <a href="http://localhost:3000/Profile">PROFILE</a>
  <a href="http://localhost:3000/posts/new">NEW POST</a>
 
  <a href="http://localhost:3000" style="float:right">TO BACK</a>
</div>

<div class="w3-light-grey w3-padding-64 w3-margin-bottom w3-center">
  <h1 class="w3-jumbo">Search image from PIXABY!</h1>
</div>

<div class="container">
  <%= @img_urls.each do |url| %>
  	<img src="<%= url %>"  style="width:30%;"/>
  <% end %>
</div>

ExperienceApp/app/views/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:blog_title, 'active') %>
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

ExperienceApp/app/views/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:blog_title, 'active') %>



<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<head>








<style>
.container {
    box-sizing: border-box;
    padding: 20px 20px;
}

input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    resize: vertical;
}



input[type=submit] {
    
    padding: 12px 20px;
    
    cursor: pointer;
    float: right;
}



.containerr {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 40px 40px; 
}



/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
    .col-25, .col-75, input[type=submit] {
        width: 100%;
        margin-top: 0;
    }
}





body{
    background-color:#CCCCCC  ;
}
ul {
    list-style-type: none;
    margin: 10;
    padding: 10;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 20px 20px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}
</style>
</head>
<body  >


<ul>
 <li><a href="http://localhost:3000/posts" >POST</a></li>

  
 <li><a href="http://localhost:3000/Profile" >PROFILE</a></li>
  <li><a href="http://localhost:3000/ricerca" >FIND INSPIRATION</a></li>
  <li><a href="http://localhost:3000/posts/new" >NEW POST</a></li>
  
 

</ul>

<br>
<br>
<br>

<div class="w3-row-padding w3-content" style="max-width:1400px">
  <div class="w3-twothird">
    <img src="https://images.pexels.com/photos/861126/pexels-photo-861126.jpeg?cs=srgb&dl=arch-architecture-blur-861126.jpg&fm=jpg"  style="width:100%">
    
   
  </div>
  <div class="w3-third">
    <div class="w3-container w3-light-grey">
        <%= render 'form', post: @post %>

        <%= link_to 'Back', posts_path %>
      
    </div>
    <br>
    <div class="w3-container w3-light-grey w3-justify">
      <h2>What can I do?</h2>
      <p class="w3-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua fai una foto!? .</p>
    </div>
    <br>
  
  </div>
</div>



</body>
</html>

ExperienceApp/app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_title, 'active') %>



<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">
            function start() {
            var A = document.getElementById('divmn');

            var isPremium = localStorage.typeU;

            if (isPremium == 'gold') {
                A.style.display = '';
            }
            else {
                alert("Un utente Free non può visionare questo elemento!");
                window.location="http://localhost:3000/Profile";
            }
        }
 </script>
<style>
ul {
    list-style-type: none;
    margin: 10;
    padding: 10;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 20px 20px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}
div.centro{
  
    
    padding-top: 50px;
    padding-right: 30px;
    padding-bottom: 50px;
    padding-left: 80px;

}
</style>
</head>
<body onload="start()">


<ul>
 <li><a href="http://localhost:3000/posts" >POST</a></li>
  
 <li><a href="http://localhost:3000/Profile" >PROFILE</a></li>
  
  <li><a href="http://localhost:3000/posts/new" >NEW POST</a></li>
  
 

</ul>

<br>

<div class="divmn">
<p id="notice"><%= notice %></p>
<div class="centro">
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body text:</strong>
  <%= @post.body_text %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>




<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> |
<%= link_to 'Destroy', post_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</div>
</div>
</body>
</html>
 