Luigi/config/routes.rb
Rails.application.routes.draw do
    get 'create' => 'sessions#create',as: :create
    get 'destroy' => 'sessions#destroy',as: :destroy
	get 'about' => 'pages#about' ,as: :about
	get 'contact' => 'pages#contact' ,as: :contact
	root to: 'posts#index'
  	resources :posts
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'

    resources :sessions, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Luigi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Luigi/app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged
	scope :most_recent, ->{ order(id: :desc)}

	def should_generate_new_friendly_id?
		title_changed?
	end

	def dysplay_day_published
		"Published  #{created_at.strftime('%-b %-d , %Y')}"
	end
	
end

Luigi/app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.typeU = '0'
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

Luigi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

Luigi/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end

	def contact
	end
end

Luigi/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url)
    end
end

Luigi/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

Luigi/app/helpers/application_helper.rb
module ApplicationHelper
end

Luigi/app/helpers/posts_helper.rb
module PostsHelper
end

Luigi/app/helpers/sessions_helper.rb
module SessionsHelper
end

Luigi/app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111;
}
</style>
</head>
<body>


<ul>
  <li><%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %></li>
  <li><%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %></li>
  <li><%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %></li>
  <li><a href="http://localhost:3000/posts/new" >NEW POST</a></li>
	
 

</ul>

<br>

</body>
</html>

Luigi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %>  |  EXPERIENCE!</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:LightGray">
    <%= render 'layouts/navbar' %>
  
    <div class="container <%= controller_name %> <% action_name %>">
    <%= yield %>
  </div>
  </body>
</html>

Luigi/app/views/pages/about.html.erb
<% provide(:about_active,'active') %>
<h1>Login Page</h1>

<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Overpass+Mono" rel="stylesheet">

<div id="wrapper">
  <div class="main-content">
    <div class="header">
      <img src="https://www.freepnglogos.com/uploads/black-instagram-logo-icon-png-10.png" style="width:5%";/>    EXPERIENCE! 
    </div>
    <br>
    <div class="l-part">
      <input type="text" placeholder="Username" class="input-1" />
      <div class="overlap-text">
        <input type="password" placeholder="Password" class="input-2" />
        <a href="#">Forgot?</a>
      </div>
      <input type="button" value="Log in" class="btn" />
    </div>
  </div>
  <div class="sub-content">
    <div class="s-part">
      Don't have an account?<a href="#">Sign up</a>
 	<div>
	      <% if current_user %>
		<li><%= current_user.name %></li>
		 
		<%= link_to "Sign out", signout_path, id: "sign_out" %>
	      <% else %>
		<%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
	      <% end %>
   </>
    </div>
  </div>
</div>




<!-- By Coding Market -->
<div class="youtube">
  <a href="https://www.youtube.com/channel/UCtVM2RthR4aC6o7dzySmExA" target="_blank">by coding market</a>
</div>

Luigi/app/views/pages/contact.html.erb
<% provide(:contact_active,'active') %>
<h1>Contact Page</h1>

<form action="/cgi-bin/FormMail.pl" method="POST">
<input type=hidden name="recipient" value="Experience@localhost.com">
<input type=hidden name="subject" value="Nuovo messaggio da Experience!">
<table border="0" cellspacing="0" cellpadding="5" align="center">
 <tr>
 <td><b> Nome e Cognome:</b></td>
 <td align="right"><input type=text name="realname"></td>
 </tr>
 <tr>
 <td><b>Email:</b></td>
 <td align="right"><input type=text name="email"></td>
 </tr>
 <tr>
 <td colspan="2"><b>Messaggio:</b></td>
 </tr>
 <tr>
 <td colspan="2"><textarea name="messaggio" cols="40" rows="5"></textarea></td>
 </tr>
 <tr>
 <td colspan="2" align="center"><input type="Submit" value="Invia"></td>
 </tr>
</table>
<input type=hidden name="required" value="email,realname,messaggio">
</form>

Luigi/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.text_field :banner_image_url %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Luigi/app/views/posts/_post.html.erb
<div class='col-sm-6 col-lg-4'>
	
	<div class="card">
		<div class="card-topper">
		<img src="<%= post.banner_image_url %>" style="width:100%;" />
				
			
		</div>
		<div class="card-block">
			
			<h4 class="card-title"><%= link_to post.title, post %></h4>
			<p class="published-date"><%= post.dysplay_day_published %></p>
			<p class="card-text"><%= truncate(post.description, length:130) %></p>
			<%= link_to 'Read' , post,class: 'btn btn-read' %>
		</div>
	</div>
</div>

Luigi/app/views/posts/edit.html.erb
<% provide(:page_title,"#{@post.title}") %>
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

Luigi/app/views/posts/index.html.erb
<% provide(:page_title,'ALL Post') %>
<% provide(:blog_active,'active') %>
<% if current_user %>
	<div class="row">
	    <%= render @posts %>
   	</div>
<% else %>
		<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1 {font-family: "Montserrat", sans-serif}
img {margin-bottom: -7px}
.w3-row-padding img {margin-bottom: 12px}
</style>
<body>

<!-- Sidebar -->
<nav class="w3-sidebar w3-black w3-animate-top w3-xxlarge" style="display:none;padding-top:150px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-black w3-xxlarge w3-padding w3-display-topright" style="padding:6px 24px">
    <i class="fa fa-remove"></i>
  </a>
  <div class="w3-bar-block w3-center">
    <a href="http://localhost:3000/Blog" class="w3-bar-item w3-button w3-text-grey w3-hover-black">Blog</a>

    
    <a href="#" class="w3-bar-item w3-button w3-text-grey w3-hover-black">Contact</a>
  </div>
</nav>

<!-- !PAGE CONTENT! -->
<div class="w3-content" style="max-width:1500px">

<!-- Header -->
<div class="w3-opacity">
<span class="w3-button w3-xxlarge w3-white w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></span> 
<div class="w3-clear"></div>
<header class="w3-center w3-margin-bottom">
  <h1><b>WELCOME!</b></h1>
  
  <p class="w3-padding-16"><button class="w3-button w3-black" onclick="myFunction()">EXPERIENCE</button></p>
</header>
</div>

<!-- Photo Grid -->
<div class="w3-row" id="myGrid" style="margin-bottom:128px">
   <div class="w3-third">
    <img src="https://images.pexels.com/photos/984539/pexels-photo-984539.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
    <img src="https://images.pexels.com/photos/1036857/pexels-photo-1036857.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
    <img src="https://images.pexels.com/photos/968243/pexels-photo-968243.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
   
  </div>

  <div class="w3-third">
    <img src="https://images.pexels.com/photos/1037999/pexels-photo-1037999.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
    <img src="https://images.pexels.com/photos/1036808/pexels-photo-1036808.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
    <img src="https://images.pexels.com/photos/994523/pexels-photo-994523.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
   
  </div>

  <div class="w3-third">
    <img src="https://images.pexels.com/photos/1011337/pexels-photo-1011337.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
    <img src="https://images.pexels.com/photos/1020323/pexels-photo-1020323.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">
    <img src="https://images.pexels.com/photos/1051075/pexels-photo-1051075.jpeg?auto=compress&cs=tinysrgb&h=350" style="width:100%">

	</div>
</div>

<!-- End Page Content -->
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-light-grey w3-center w3-opacity w3-xlarge" style="margin-top:128px"> 
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
  <p class="w3-medium">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>
 
<script>
// Toggle grid padding
function myFunction() {
    var x = document.getElementById("myGrid");
    if (x.className === "w3-row") {
        x.className = "w3-row-padding";
    } else { 
        x.className = x.className.replace("w3-row-padding", "w3-row");
    }
}

// Open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.width = "100%";
    document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>
<% end %>

Luigi/app/views/posts/new.html.erb
<% provide(:page_title,'New Post') %>
<% provide(:blog_active,'active') %>
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

Luigi/app/views/posts/show.html.erb
<% provide(:page_title,@post.title) %>
<% provide(:blog_active,'active') %>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-leg-2 text-xs-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.dysplay_day_published %></p>
		<%= @post.body %>
	</div>
	
</div>
<br>
<div>
	
	<%= link_to 'Remove', post_path(@post), method: :delete , data: { confirm: 'Sei sicuro di voler cancellare questo post?'} ,class:'btn btn-sm btn-danger'%>
</div>